[general]
import = [
  "~/.config/alacritty/themes/kanagawa_dragon.toml"
]

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

[window]
dynamic_padding = true
decorations = "none"
startup_mode = "Windowed"
opacity = 1
