theme = "bogster"

[editor]
line-number = "relative"
mouse = true
cursorline = true
scrolloff = 5
auto-save = true
completion-trigger-len = 1
auto-pairs = true
insert-final-newline = true
clipboard-provider = "x-clip"
middle-click-paste = true

[editor.whitespace]
render = "none"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control", "diagnostics", "position-percentage", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.file-picker]
hidden = false

[keys.normal]
"C-s" = ":w"
"C-q" = ":q"
"C-n" = ":bnext"
"C-p" = ":bprev"
