[[language]]
name = "markdown"
language-id = "markdown"
file-types = ["md"]
language-servers = ["marksman", "markdown-oxide", "ltex-ls-plus"]

[language-server.ltex-ls-plus.config]
ltex.language = "en-CA"
ltex.enabledRules = { "en-CA" = { "SPELLING" = true, "GRAMMAR" = true, "TYPOGRAPHY" = true } }

[[language]]
name = "toml"
language-servers = ["taplo"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "ltex-ls-plus"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{file}"] }
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = "stylelint", args = ["--fix", "--stdin", "--stdin-filename", "{file}"] }
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "scss"
language-servers = ["vscode-css-language-server"]
formatter = { command = "stylelint", args = ["--fix", "--stdin", "--stdin-filename", "{file}"] }
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{file}"] }
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "{file}"] }
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-langserver"]
auto-format = true
formatter = { command = "goimports" }
indent = { tab-width = 4, unit = "\t" }
